export {
  BANNER_COST_CLAIM,
  BANNER_COST_MOVE,
  BANNER_PER_PRODUCER,
  BANNER_PER_PRODUCER_AT_FORGE,
  calculateBannerProduction,
  calculateMovementCost,
  canAffordClaim,
  canAffordCombatSpend,
  canAffordMovement,
  discardUnspentBanners,
  generateBanners,
  spendBanners,
  spendBannersForClaim,
  spendBannersForCombat,
  spendBannersForMovement,
} from './resources.js';
