#!/usr/bin/env node
/**
 * sim-v3.mjs — run a deterministic v3 balance/strategy sweep and write a report.
 *
 * The v3 sim LIBRARY is pure TS under src/v3/sim/; this runner is a plain Node ESM
 * script (so it may use fs/timestamps without touching the §7 determinism invariant
 * that governs src/v3). It imports the COMPILED library from dist/ — so this runner
 * is invoked by `npm run sim:v3`, which builds first (`tsc && node scripts/sim-v3.mjs`).
 *
 * This is the v3 counterpart of scripts/sim.mjs. It does NOT depend on the v2 sim
 * (`scripts/sim.mjs`) or the v2 `gen:data` step — the v3 archetypes are the committed
 * src/v3/sim/archetypes.gen.ts, regenerated by the v3 codegen path (not this runner).
 *
 * Usage: node scripts/sim-v3.mjs [baseSeed] [seedCount] [--quick] [--bloodpact] [--herald] [--report-only]
 *   baseSeed       default 20260622   (seed list is derived deterministically from it)
 *   seedCount      default 40         (games per matchup-cell)
 *   --quick        small set (fast smoke of the whole pipeline)
 *   --bloodpact    run the blood_pact traitor sweep instead of the competitive sweep
 *   --herald       run the ADVANCED Herald-enabled variant (T2-3; default is the
 *                  3-archetype herald-OFF game — the game's default balance)
 *   --report-only  print the report but never fail on a band miss (Stage V3-4 is a
 *                  pure DIAGNOSTIC — the untuned engine is EXPECTED to miss bands)
 *
 * Exit code: non-zero ONLY if any game fails to terminate (a real bug). Stage V3-4
 * does NOT tune, so a §9 band miss is reported, never failed (unlike the v2 runner,
 * which guards the locked Shadowking band).
 *
 * Determinism: the seed LIST is generated via SeededRandom(baseSeed) — never
 * Math.random — so a given (baseSeed, seedCount) reproduces the same sweep.
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { SeededRandom } from '../dist/utils/seeded-random.js';
import { runSweep } from '../dist/v3/sim/sweep.js';
import { standardMatchups, MIXED_CANONICAL, bloodPactMatchups } from '../dist/v3/sim/matchups.js';
import {
  summarize, renderMarkdown, summarizeBloodPact, renderBloodPactMarkdown,
} from '../dist/v3/sim/report.js';

const ROOT = process.cwd();
const args = process.argv.slice(2);
const quick = args.includes('--quick');
const bloodpact = args.includes('--bloodpact');
const herald = args.includes('--herald');
const positional = args.filter(a => !a.startsWith('--'));

const baseSeed = Number(positional[0] ?? 20260622) || 20260622;
const seedCount = Number(positional[1] ?? (quick ? 6 : 40)) || (quick ? 6 : 40);

// Deterministic seed list from the base seed (no Math.random).
const rng = new SeededRandom(baseSeed);
const seeds = Array.from({ length: seedCount }, () => rng.int(0, 0x7fffffff));

const playerCounts = quick ? [4] : [2, 3, 4];
const modes = bloodpact ? ['blood_pact'] : ['competitive'];
const matchups = bloodpact ? bloodPactMatchups() : (quick ? [MIXED_CANONICAL] : standardMatchups());

console.log(`\n=== v3 ${bloodpact ? 'blood-pact' : 'balance'} sweep === baseSeed=${baseSeed} seeds=${seedCount} ` +
  `counts=${playerCounts.join('/')} matchups=${matchups.length}${herald ? ' [herald-ON variant]' : ''}${quick ? ' [quick]' : ''}`);

const t0 = Date.now();
const rows = runSweep({ seeds, playerCounts, modes, matchups, heraldEnabled: herald });
const elapsedMs = Date.now() - t0;

const runId = `v3-s${baseSeed}-n${seedCount}${bloodpact ? '-bp' : ''}${herald ? '-herald' : ''}${quick ? '-quick' : ''}`;
const meta = { runId, baseSeed, seedCount, playerCounts, modes, matchupCount: matchups.length, heraldEnabled: herald };

const outDir = resolve(ROOT, 'sim-results', runId);
mkdirSync(outDir, { recursive: true });
writeFileSync(resolve(outDir, 'rows.json'), JSON.stringify(rows, null, 2) + '\n');

const hitGuard = rows.filter(r => r.hitGuard).length;

let md;
if (bloodpact) {
  const bp = summarizeBloodPact(rows);
  md = renderBloodPactMarkdown(bp, meta);
  writeFileSync(resolve(outDir, 'summary.json'), JSON.stringify(bp, null, 2) + '\n');
  writeFileSync(resolve(outDir, 'REPORT.md'), md);
} else {
  const summary = summarize(rows);
  md = renderMarkdown(summary, meta);
  writeFileSync(resolve(outDir, 'summary.json'), JSON.stringify(summary, null, 2) + '\n');
  writeFileSync(resolve(outDir, 'REPORT.md'), md);
}

console.log(`\n${rows.length} games in ${(elapsedMs / 1000).toFixed(1)}s → sim-results/${runId}/`);
console.log('\n' + md);

// Stage V3-4 is a pure diagnostic: fail ONLY on a non-termination guard (a real bug).
// Band misses are EXPECTED on the untuned engine and are reported, not failed.
if (hitGuard > 0) {
  console.error(`\n✗ ${hitGuard} game(s) hit the step guard without terminating — a real bug to fix.`);
}
process.exit(hitGuard > 0 ? 1 : 0);
